language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - pip install -r requirements_dev.txt
  - pip install coveralls
script: nosetests
after_success:
  - tox -e coverage
  - coveralls
